"""M3-01 fails-before and passes-after tests for vbb-adversarial-gate.py
(nested `adversarial:` block unwrap).

The v1.1 canonical structure is a nested YAML block starting with `adversarial:`,
which parses to `{"adversarial": {...}}`. The validator must unwrap this single-key
mapping to access the actual fields.

Tests use subprocess invocation to exercise the validator's real exit code,
text output, and structural verdict.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent


# A canonical v1.1 closeout body, generated by the canonical template
# (re-implemented here to avoid coupling tests to file reads).
CANON_V11_BODY = """```yaml
adversarial:
  level: "A2"
  campaign_ref: "test-canon"
  corpus_version: "v1.1"
  exploration_performed: true
  surfaces_declared:
    - "x.py"
  surfaces_unexplored: []
  residual_uncertainty: "none"
  findings: []
  verdict: "PASS_ADVERSARIAL"
  non_claim: "absence of finding is bounded evidence, never proof"
  attacker_identity:
    agent: "external attacker"
    llm: "anthropic/claude-3-5-sonnet"
    provider: "anthropic"
    system_prompt_version: "attack-falsifier-v1"
    session: "sess-abc12345"
  defender_identity:
    agent: "implementer"
    llm: "minimax/MiniMax-M3"
    provider: "minimax"
    system_prompt_version: "implementer-v1"
    session: "sess-impl-xyz"
```
```"""


def _write_closeout(tmp_path: Path, body: str) -> Path:
    (tmp_path / "01_INTAKE.md").write_text("# stub intake\n", encoding="utf-8")
    (tmp_path / "07_CLOSEOUT.md").write_text(body, encoding="utf-8")
    return tmp_path


def _run_validator(
    run_dir: Path, extra_args: list[str] | None = None
) -> tuple[int, str]:
    args = ["python", "tools/vbb-adversarial-gate.py", str(run_dir)]
    if extra_args:
        args.extend(extra_args)
    proc = subprocess.run(
        args,
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout + proc.stderr


def _passes(text: str) -> set[str]:
    return set(
        re.findall(r"^\s*(?:\[[A-Za-z0-9]+\]\s*)?PASS\s+(\S+):", text, re.MULTILINE)
    )


def _fails(text: str) -> set[str]:
    return set(
        re.findall(r"^\s*(?:\[[A-Za-z0-9]+\]\s*)?FAIL\s+(\S+):", text, re.MULTILINE)
    )


# A. Nested block (v1.1 canonical) — must PASS structural gates
def test_adversarial_gate_parses_nested_adversarial_block(tmp_path: Path):
    """vbb-adversarial-gate.py must extract fields from a YAML block whose first
    line is `adversarial:` (v1.1 canonical). Fails-BEFORE: empty PASS set."""
    _write_closeout(tmp_path, CANON_V11_BODY)
    rc, text = _run_validator(tmp_path)
    p = _passes(text)
    expected = {
        "adv-block-exists",
        "adv-level-valid",
        "adv-campaign-ref",
        "adv-corpus-version",
        "adv-surfaces-declared",
        "adv-surfaces-unexplored",
    }
    assert expected.issubset(p), (
        f"Fails-BEFORE/regression: {expected} not all in PASSES ({p})"
    )


# B. Hybrid structure: nested `adversarial:` + extra root-level siblings
def test_adversarial_gate_handles_hybrid_safely(tmp_path: Path):
    """A hybrid YAML block must not silently absorb extra top-level keys."""
    hybrid = (
        "```yaml\n"
        "adversarial:\n"
        "  level: A2\n"
        "  campaign_ref: test\n"
        "extra_top_level: should_not_be_there\n"
        "```\n"
    )
    _write_closeout(tmp_path, hybrid)
    rc, text = _run_validator(tmp_path)
    # We don't expect any gate_id "adv-extra-top-level-allowed".
    assert "adv-extra-top-level-allowed" not in text


# C. Empty adversarial block must FAIL closed
def test_adversarial_gate_rejects_empty_adversarial_block(tmp_path: Path):
    """`adversarial: {}` must FAIL closed: the shape gate fires (empty mapping)."""
    _write_closeout(tmp_path, "```yaml\nadversarial: {}\n```\n")
    rc, text = _run_validator(tmp_path)
    f = _fails(text)
    # Empty mapping triggers adv-block-shape (cannot extract level).
    assert "adv-block-shape" in f or "adv-level-valid" in f, (
        f"Fails-BEFORE: expected adv-block-shape or adv-level-valid in fails ({f})"
    )


# D. adversarial: "A2" (scalar type) must FAIL closed
def test_adversarial_gate_rejects_string_adversarial(tmp_path: Path):
    """`adversarial: "A2"` (scalar) must FAIL closed."""
    _write_closeout(tmp_path, '```yaml\nadversarial: "A2"\n```\n')
    rc, text = _run_validator(tmp_path)
    f = _fails(text)
    assert ("adv-block-shape" in f) or ("adv-level-valid" in f)


# E. Root without `adversarial:` wrapper must FAIL closed
def test_adversarial_gate_rejects_root_level_fields(tmp_path: Path):
    """A YAML block without `adversarial:` wrapper (raw level at root) must FAIL
    closed (not silently treated as the adversarial fields)."""
    body = "```yaml\nlevel: A2\ncampaign_ref: test\nstatus: PASS_ADVERSARIAL\n```\n"
    _write_closeout(tmp_path, body)
    rc, text = _run_validator(tmp_path)
    f = _fails(text)
    # adv-block-exists must FAIL because no `adversarial:` key was detected.
    assert "adv-block-exists" in f


# F. Text/JSON/exit-code coherence on a valid v1.1 closeout
def test_adversarial_gate_consistency_text_json_exit(tmp_path: Path):
    """Validator exit code, JSON verdict, and human summary must agree.

    Valid v1.1 closeout must produce exit code 0 with verdict PASS."""
    _write_closeout(tmp_path, CANON_V11_BODY)
    rc, text = _run_validator(tmp_path)
    assert re.search(r"verdict:", text, re.IGNORECASE), "missing verdict line"
    # If structural gates all pass, exit code 0; verdict PASS in text.
    passes = _passes(text)
    if "adv-level-valid" in passes:
        assert rc == 0, f"with structural passes, expected exit 0, got {rc}"
        verdict_line = text.splitlines()[0]
        assert "PASS" in verdict_line


def _bound_body(run_id: str, commit: str) -> str:
    return CANON_V11_BODY.replace(
        "  defender_identity:\n",
        "  certification:\n"
        '    status: "NOT_CERTIFIED"\n'
        "    bound_to:\n"
        f'      run_id: "{run_id}"\n'
        f'      commit: "{commit}"\n'
        '      corpus_version: "v1.1"\n'
        "  defender_identity:\n",
    )


def _git_bound_run(tmp_path: Path) -> tuple[Path, str]:
    repo = tmp_path / "repo"
    run = repo / "runs" / "declared-run"
    run.mkdir(parents=True)
    subprocess.run(["git", "init", str(repo)], check=True, capture_output=True)
    subprocess.run(
        ["git", "-C", str(repo), "config", "user.name", "VBB Test"], check=True
    )
    subprocess.run(
        ["git", "-C", str(repo), "config", "user.email", "vbb@example.invalid"],
        check=True,
    )
    (repo / "candidate").write_text("candidate\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "candidate"], check=True)
    subprocess.run(
        ["git", "-C", str(repo), "commit", "-m", "candidate"],
        check=True,
        capture_output=True,
    )
    commit = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    _write_closeout(run, _bound_body(run.name, commit))
    return run, commit


def test_expected_commit_binds_the_declared_run(tmp_path: Path):
    run, commit = _git_bound_run(tmp_path)
    rc, text = _run_validator(
        run,
        ["--runs-dir", str(run.parent), "--expected-commit", commit, "--strict"],
    )
    assert rc == 0, text
    assert "release-subject-binding" in text


def test_expected_commit_rejects_wrong_sha(tmp_path: Path):
    run, _ = _git_bound_run(tmp_path)
    rc, text = _run_validator(
        run,
        [
            "--runs-dir",
            str(run.parent),
            "--expected-commit",
            "b" * 40,
            "--strict",
        ],
    )
    assert rc == 2
    assert "release-subject-binding" in text
    assert "does not match expected commit" in text


def test_expected_commit_rejects_external_run_directory(tmp_path: Path):
    run, commit = _git_bound_run(tmp_path)
    rc, text = _run_validator(
        run,
        ["--expected-commit", commit, "--strict"],
    )
    assert rc == 3
    assert "cannot resolve a run directory" in text


def test_expected_commit_rejects_implicit_latest(tmp_path: Path):
    _write_closeout(tmp_path, _bound_body(tmp_path.name, "a" * 40))
    proc = subprocess.run(
        [
            "python",
            "tools/vbb-adversarial-gate.py",
            "--latest",
            "--expected-commit",
            "a" * 40,
            "--strict",
        ],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    assert proc.returncode != 0
    assert "explicit run" in (proc.stdout + proc.stderr)
